// <auto-generated />
namespace Follower_Analyzer_for_Instagram.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class NewFields : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NewFields));
        
        string IMigrationMetadata.Id
        {
            get { return "202005281358030_NewFields"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
